.npmignore

I brought exclusions forward from the `.gitignore` file and tweaked it to be appropriate for npm.
re: @bengummer's list, imo the babel and eslint configs *should* be published to npm since we're publishing source, and they describe how it should be interpreted.

Update .npmignore, fixes #16

---

README.md
src/state/action-creators.js
src/state/get-new-home-client-offset.js
src/state/hook-middleware.js
src/state/reducer.js
src/types.js
src/view/drag-handle/drag-handle-types.js
src/view/drag-handle/drag-handle.jsx
src/view/draggable/connected-draggable.js
src/view/draggable/draggable-types.js
src/view/draggable/draggable.jsx
src/view/draggable/placeholder.jsx
src/view/droppable/connected-droppable.js
stories/components/quote-item.jsx
test/unit/integration/hooks-integration.spec.js
test/unit/state/get-new-home-client-offset.spec.js
test/unit/state/hook-middleware.spec.js
test/unit/view/connected-draggable.spec.js
test/unit/view/connected-droppable.spec.js
test/unit/view/drag-handle.spec.js
test/unit/view/unconnected-draggable.spec.js

Currently drag 'cancel' actions are not animated. This behaviour was accounted for a one point before this library was public. It must have regressed when I made some serious changes to draggable and drag handle around animations and pointer events
This PR also improves a few minor performance issues
- selectors are no longer partially shared across connected components
- `user-select: none` on placeholder

Animate cancel

---

README.md
src/view/draggable/draggable-types.js
src/view/draggable/draggable.jsx
test/unit/view/unconnected-draggable.spec.js

`Draggables` with top or left margin value will now be positioned correctly. Previously this was not being accounted for in the `top` / `left` positioning of the `Draggable`. 
For more details read the `DraggingStyle`.

Draggables allowing margin top and left

---

package.json
src/view/draggable/draggable.jsx
src/view/droppable/droppable.jsx
test/unit/view/drag-drop-context.spec.js
yarn.lock

This is in anticipation of #8 
This removes all the yuck deprecation warnings in the tests and development environments.
It also opens the way to React 16! I bumped to React 16 and everything looks good! I will not to React 16 until it is stable - but it good to know we are ready to go
(how I checked react 16: https://github.com/facebook/react/issues/10294)
It was not a super in depth analysis - but it looks good on initial pass.
Some of the tests break moving to React 16 - but it looks like jest was throwing and error because the enzyme React dependency was not met correct - which makes sense.

using recommended packages to avoid deprecation warnings

---

stories/5-multiple-vertical-lists-story.js
stories/src/multiple-vertical/quote-app.js
stories/src/multiple-vertical/quote-list.js

Just adding the story for testing - the behaviour isn't currently implemented.

add story for dragging between two vertical lists

---

src/state/create-store.js

Should take care of issue #65 
Checking that the window is defined before accessing it so that the module doesn't break on the server.

Checking that the window is defined before accessing it.

---

README.md
src/state/create-store.js
test/setup.js
test/unit/integration/__snapshots__/server-side-rendering.spec.js.snap
test/unit/integration/server-side-rendering.spec.js

@romellogood recently added a change #65 that enabled server side rendering to work correctly. This pull request builds on that and adds some tests to ensure that we do not accidentally break server side rendering going forward.

adding tests for server side rendering

---

package.json
yarn.lock

All cli tests passed.
Hand tests is ok.
- Chrome, Firefox, Safari (mac)
- IE 11 (win7 in VirtualBox)
I did't change `react-dom` version, because `react-dom/test-utils` used in tests (since 15.5)
But I made hand tests with `react-dom 15.4.0`

Decrease minimal react version ( closed #84 )

---

src/view/droppable/connected-droppable.js
test/unit/view/connected-droppable.spec.js

Without this the droppable placeholder is too big

droppable placeholder now takes up correct size

---

src/state/reducer.js

Previously which draggable you where over was based on the mouse selection position. Are more natural way is to base it on the center position of the draggable.
I found this as part of #92 but I wanted to get this change in so people can start using it before the refactor is done

base what droppable you are over is based on center position of draggable

---

stories/src/multiple-horizontal/quote-app.jsx
stories/src/primatives/author-list.jsx

The issue arose because because in the horizontal plane the width of elements within a scroll container doesn't extend beyond their parent, even if they should be wider.

fix horizontal list story

---

src/state/dimension.js
src/state/is-within-visible-bounds-of-droppable.js
src/state/move-cross-axis/get-best-cross-axis-droppable.js
src/state/position.js
src/state/spacing.js
src/types.js
stories/src/primatives/quote-list.jsx
test/unit/state/dimension.spec.js
test/unit/state/is-within-visible-bounds-of-droppable.spec.js
test/unit/state/position.spec.js
test/unit/state/spacing.spec.js
test/utils/dimension.js

Fixes #122. 
@jaredcrowe can you please verify that this is what we want to be doing. I think it is. I had a play with the storybooks and and it yields the expected results. 
This PR is not quite done - I have not finished fixing all of the tests in `is-within-visible-bounds-of-droppable.spec`. Can you please update the remaining ones?
Cheers

dimension clipping now considers margins

---

src/view/drag-handle/drag-handle.jsx

Fixes #139. 
Should a test be created for this new use-case?
If yes, I am unsure of how best to test this new functionality as `this.props.draggableRef` is not defined when running jest. Hence, the undefined check, as otherwise many of the drag-handle tests will fail.

Incorrect Binding to Window Event Listeners Fix

---

src/state/is-within-visible-bounds-of-droppable.js
src/state/move-cross-axis/get-best-cross-axis-droppable.js
src/state/spacing.js
stories/5-multiple-vertical-lists-story.js
test/unit/state/move-cross-axis/get-best-cross-axis-droppable.spec.js
test/unit/state/spacing.spec.js

Keyboard drag dimension clipping fix

---

README.md

Please ignore the first paragraph.

Added patching inputs inside Draggable example

---

README.md

The feature has been implemented with v2.2.0 and therefore the
disclaimer is no longer necessary.

Remove disclaimer for moving between droppables

---

README.md

The `getItemStyle` in README.md had a bug when I tried it but the one in the WebpackBin code worked perfectly. This commit brings the change in the WebpackBin example to README.md.

Update README.md to match WebpackBin example

---

src/state/action-creators.js
src/state/reducer.js
src/types.js
test/unit/state/action-creators.spec.js
test/utils/dimension.js

Less `setTimeout` craziness - and a much more solid flow as a result!

Improved drag flow

---

package.json
yarn.lock

I have recently started to use react-beautiful-dnd, and found that I was getting flow errors from raf-schd:
```
Error: node_modules/raf-schd/test/index.spec.js:2
2: import { replaceRaf } from 'raf-stub';
^^^^^^^^^^ raf-stub. Required module not found
```
It seems that version 2.0.1 was publishing its test files to npm.  This version fixes that problem.

⬆️ Upgrade raf-schd to 2.0.2

---

.travis.yml

We are getting this error when attempting to release on travis:
```
travis_fold:end:dpl.1
travis_fold:start:dpl.2
[33mPreparing deploy[0m
NPM version: 5.3.0
Authenticated with email alexreardon@gmail.com
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
warning: CRLF will be replaced by LF in node_modules/chain-function/.gitattributes.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/chain-function/.npmignore.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in node_modules/chain-function/index.js.
The file will …
```

installing rimraf before deploy

---

src/view/drag-drop-context/drag-drop-context.jsx
src/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js
src/view/draggable/draggable-types.js
src/view/droppable-dimension-publisher/droppable-dimension-publisher-types.js
src/view/droppable/droppable-types.js
src/view/moveable/moveable-types.js

This was caused by using the recommended flow pattern:
`import * as React from 'react';`
However, doing this causes deprecation warnings to fire.
https://github.com/facebook/flow/issues/4673
Now [explicitly importing required types](https://github.com/facebook/flow/issues/4673#issuecomment-323850646) from react rather than using the `import *` method.

explicitly importing react types to avoid deprecation warnings

---

.eslintignore
.gitignore
package.json
rollup.config.js
yarn.lock

Added distribution bundle.
https://github.com/atlassian/react-beautiful-dnd/issues/142

chore(build): add distribution files

---

README.md
package.json
rollup.config.js
yarn.lock

Fixing a minor issue @vinifala where the script would 💥 if `process.env` was not set. Just setting it to production for simplicity

fixing error in dist build when process.env is not available

---

README.md

Adding a direct link to update notes. Closes #262 
Fixes basic example [comment](https://github.com/atlassian/react-beautiful-dnd/commit/0fb4dc75ea9b625f64cac48602635ac2822f26ec#commitcomment-268360260)

fixing basic example. adding link to upgrade notes

---

src/state/dimension-marshal/dimension-marshal.js
src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx
src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx
test/unit/view/dimension-marshal.spec.js
test/unit/view/draggable-dimension-publisher.spec.js
test/unit/view/droppable-dimension-publisher.spec.js

Closes #260.
Removes error in experimental behaviour by just removing it altogether. It was documented as not supported.
There are lots of scenarios that are not catered for in the current implementation so I think it best to remove it and work on adding support for it when we move towards #68

disabling partially implementated experimental behaviour

---

package.json
rollup.config.js
yarn.lock

- using https://github.com/rollup/rollup-plugin-strip plugin to remove console from builds

strip console from builds

---

README.md

Also pulls up a link to the positioning notes toward the top, making it more visible.

Add a note about table support

---

package.json
yarn.lock

Simple referencing to source is in a way cleaner way to distribute flow typed than copying source code over and over again.

Simplify flow types distribution

---

src/view/drag-drop-context/drag-drop-context.jsx

Now that we call the dimension marshal after the hook it is possible to have the dimension marshal pick up post drop reorder changes. It would cause some console.warn messages. This fixes that.
We really need to fix our control flow generally as this is getting messy. But i'll leave that for another day

now calling dimension publisher first when drag is ending

---

.eslintrc
flow-typed/npm/@storybook/react_v3.x.x.js
flow-typed/npm/enzyme_v3.x.x.js
flow-typed/npm/invariant_v2.x.x.js
flow-typed/npm/jest_v22.x.x.js
flow-typed/npm/prop-types_v15.x.x.js
flow-typed/npm/react-redux_v5.x.x.js
flow-typed/npm/react-test-renderer_v16.x.x.js
flow-typed/npm/redux_v3.x.x.js
flow-typed/npm/reselect_v3.x.x.js
package.json
src/state/dimension-marshal/dimension-marshal.js
src/state/dimension.js
src/state/get-new-home-client-center.js
src/state/reducer.js
src/view/drag-handle/sensor/create-mouse-sensor.js
src/view/drag-handle/sensor/create-touch-sensor.js
src/view/draggable/connected-draggable.js
src/view/draggable/draggable.jsx
src/view/droppable/connected-droppable.js
src/view/droppable/droppable.jsx
src/view/moveable/moveable-types.js
src/view/moveable/moveable.jsx
test/unit/view/drag-drop-context.spec.js
yarn.lock

- upgraded flow
- upgraded definitions with `flow-typed install --skip`
- fixed opaque types of `requestAnimationFrame` and `setTimeout`
- removed $ExpectError suppressions which may not exists in user config
- removed $FlowFixMe suppressions because sometimes they force flow recheck infinitely (personal experience)
- fixed a few suppressed errors
- prevented react-redux errors with more safe `any`, I think it's ok since you annotate so much
P.S. New react-redux definitions are still broken, probably because they do not cover all cases

Upgrade flow

---

docs/guides/how-we-use-dom-events.md
src/view/drag-handle/sensor/create-touch-sensor.js

Fixes #413 
This is a hack to get things working again. I cannot seem to find the exact root cause. There is a bug that I have noticed and raised with webkit. If that is fixed then I can remove the hack. However, my find does not explain why it worked on iOS 11.2. I am trying really hard to find an answer

iOS 11.3 fix

---

.babelrc
.eslintignore
.gitignore
.size-snapshot.json
package.json
rollup.config.js
yarn.lock

Ref #405 
Closes https://github.com/atlassian/react-beautiful-dnd/pull/428

Provide cjs and esm bundles with information about treeshakability

---

.size-snapshot.json
README.md
package.json
rollup.config.js
yarn.lock

this is to preserve the public usage of `/dist/react-beautiful-dnd.js` as a umd build. I think this is a good complement to `/dist/react-beautiful-dnd.min.js` which is also a umd build. At least it keeps parity for now and we can rethink what we want to do
/cc @TrySound

removing .umd suffix from umd build

---

package.json
rollup.config.js
yarn.lock

Upgrade size snapshot plugin

---

.stylelintrc
package.json
stories/1-single-vertical-list-story.js
stories/src/accessible/task-list.jsx
stories/src/accessible/task.jsx
stories/src/board/board.jsx
stories/src/multi-drag/task.jsx
stories/src/portal/portal-app.jsx
stories/src/primatives/author-list.jsx
stories/src/primatives/quote-item.jsx
stories/src/primatives/quote-list.jsx
stories/src/primatives/title.jsx
stories/src/table/with-dimension-locking.jsx
stories/src/table/with-fixed-columns.jsx
stories/src/table/with-portal.jsx
stories/src/vertical-nested/quote-list.jsx
yarn.lock

close #373 
Hi! This is an awesome library, and I'm trying to contribute. The following is the instruction of this PR. 
1. `stylelint` only runs with the files in `/stories`, because it seems to be that no other place uses CSS.
2. Since the latest `stylelint` seems to have a [bug](https://github.com/stylelint/stylelint/issues/3252) with [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components), so I installed `stylelint@9.1.3` for now.
3. Add `/*stylelint disabled*/` in several places to prevent some strange or unnecessary `stylelint` errors.
Please let me know if there are any questions. Thanks!

Add stylelint

---

test/browser/simple-vertical-list-with-keyboard.spec.js

Hey @alexreardon ,
looking at stackoverflow and I found this:
https://stackoverflow.com/questions/49603939/jest-async-callback-was-not-invoked-within-the-5000ms-timeout-specified-by-jest
I needed to extend the timeout in the jest runner itself. Hope it will fix this.
Feel free to create an issue about adding cypress tests and assign it to me.

Extend Jest timeout

---

.babelrc.js
.size-snapshot.json
package.json
rollup.config.js
yarn.lock

4kb less to parse, 1kb less to load in production

Replace invariant with shorter version in production

---

.size-snapshot.json
src/debug/timings.js

Inlining `NODE_ENV` comparison allows uglify to eliminate
unused code in production.

Eliminate timings in production bundle

---

.size-snapshot.json
src/state/create-store.js
src/state/reducer.js
test/unit/state/middleware/hooks.spec.js
test/unit/state/middleware/pending-drop.spec.js
test/unit/state/middleware/style.spec.js

Disabling the uncompleted feature for 8.0 #484

Disabling dynamic changes

---

.size-snapshot.json
src/view/drag-handle/sensor/create-keyboard-sensor.js
src/view/drag-handle/sensor/create-mouse-sensor.js
src/view/drag-handle/sensor/create-touch-sensor.js
src/view/draggable/draggable-types.js
test/unit/view/drag-handle/drag-handle.spec.js

Fixes #615 /cc @eduludi
We added some unnecessary, overly defensive event blocking which broke some nested interactive element experiences. These unnecessary checks have been removed

unwinding event blocking if cannot drag. Fixes #615

---

src/state/middleware/hooks.js
src/state/reducer.js

hook functions are now called after the reducer

---

src/state/reducer.js
src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx

fixing invariant check in reducer. Fixes #617

---

README.md

Hey Alex,
Here it is.
Thanks for creating this awesome library! Can't wait for the docs to come out. 
Andy

Typescript example (compared with master)

---

README.md
docs/guides/hooks.md
src/types.js

Addresses #695.
edit: Also didn't realize subsequent commits to my fork would be added to the PR...but I was going to submit a new PR for the commit anyway. It's a small README change that clarifies that a drag handle should not be an interactive element. Something I discovered after 30 minutes of wondering why my `button` drag handle was not working.

Update Hook types to return `mixed` vs `void` (addresses #695)

---

website/src/components/sidebar/link-list.jsx
website/src/components/sidebar/reorderable-links.jsx

I found the underlying issue why I could not have reordering in the navigation:
https://github.com/atlassian/react-beautiful-dnd/issues/757
Once that is fixed we can add reordering back @pksjce

Reorderable links attempt

---

docs/patterns/multi-drag.md
stories/src/multi-drag/task.jsx

Closes #769 by updating the multi-drag story & pattern to support platform specific modifiers to toggle selection in a group.

Modify multi-drag pattern to support windows specific modifier

---

.flowconfig
package.json
src/view/drag-handle/util/get-drag-handle-ref.js
src/view/draggable/connected-draggable.js
src/view/draggable/draggable-types.js
src/view/droppable/connected-droppable.js
src/view/droppable/droppable-types.js
stories/src/primatives/author-list.jsx
stories/src/vertical-nested/quote-app.jsx
stories/src/vertical-nested/quote-list.jsx
test/test_flow.js
test/unit/state/middleware/responders/abort.spec.js
test/unit/state/middleware/responders/announcements.spec.js
test/unit/state/middleware/responders/flushing.spec.js
test/unit/state/middleware/responders/repeated-use.spec.js
test/unit/view/draggable/drag-handle-connection.spec.js
website/src/components/examples/primatives/author-list.jsx
website/src/pages/private.jsx
website/src/templates/markdown.jsx

Currently `Droppable` and `Draggable` components are treated as `any`
which a makes development less safer.
In this diff I with @istarkov help found a way to cover connected
components with default props without loosing type information.
A few basic flow tests will let to not remove this info accidentally.
As a result unused type property was result from some stories.
Some error suppressions are not necessary so I removed them.

Correctly expose Droppable and Draggable component types

---

README.md

As of release v10 the `Array.prototype.find` polyfill for IE 11 is no longer needed
see: https://github.com/atlassian/react-beautiful-dnd/issues/724#issuecomment-439733509

Updating README remove note about polyfill for IE 11

---

README.md
docs/guides/responders.md
docs/patterns/multi-drag.md
docs/patterns/tables.md

I updated the non root-relative ones in README.md as well even though they weren't broken just so they don't break if they're ever extracted out into their own document.

Fix dead doc links that were not root-relative

---

src/view/droppable-dimension-publisher/get-dimension.js

We're forking your amazing repo and need to add some features based on our product logic, and then I found a potential bug, which I spent a lot of time debuging.
The default container supporting horizontal scroll is the window, which would not trigger any bugs currently. But I think it would be stricter to code it this way. Pls take a look and see if I'm doing this correctly.

fix: droppable-get-dimension withScroll

---

README.md

Real small grammar change in the main docs

docs: tweak to grammar in onClick section of README

---

docs/guides/how-we-use-dom-events.md

that impact >are< drag are events that cancel a drag such as >`reize`< or `orientationchange` events.

Fixing typo

---

CONTRIBUTING.md

React-motion has been replaced with css animations.

Drop react-motion from the Technologies list in CONTRIBUTING section

---

docs/patterns/using-a-portal.md

The link to the portal usage source was broken, This PR fixes that and another typo in the portal documentation.

Fix broken example source link

---

docs/api/drag-drop-context.md

The link to the react-redux `Provider` component is no longer valid.

Fix broken link to Provider component

---

docs/about/installation.md
docs/api/drag-drop-context.md
docs/api/droppable.md
docs/guides/combining.md
docs/guides/drop-animation.md
docs/support/media.md

Adding some more function component examples to the docs

Function components in docs

---

docs/api/drag-drop-context.md

Moved the 's' in Responders heading inside the back-ticks

Fix heading styling

---

src/view/use-drag-handle/use-focus-retainer.js
test/unit/view/drag-handle/focus-management.spec.js

drag handle no longer stealing focus on mount from autoFocus elements

---

src/view/use-droppable-dimension-publisher/use-droppable-dimension-publisher.js
src/view/use-previous-ref.js

ExpectError is not always defined in user config and flow fails there.
MutatableRefObject is just exact object with current field. I don't
think it will be exported.
```js
type MutatableRefObject<T> = {| current: T |};
```

Remove custom ExpectError from source code

---

src/state/get-displacement.js
test/unit/state/get-displacement/started-displaced.spec.js
test/unit/state/get-displacement/visibility-overscanning.spec.js

fixing incorrect visibility detection for horizontal lists

---

src/view/scroll-listener.js

Logic from https://github.com/atlassian/react-beautiful-dnd/pull/1308 targeting `virtual` branch.
Not clear to me how to test this, as `getWindow` doesn't seem to be being used in this branch.

Fix IE11 autoscroll behaviour (v12)

---

docs/guides/common-setup-issues.md

The documentation was not updated to reflect the fact that `react-beautiful-dnd` now uses hooks and breaks on `React <= 16.8.5`.

Update common setup issues documentation

---

docs/support/media.md
src/view/use-announcer/use-announcer.js

fixing issue with announcer and hot module reloading

---

docs/guides/responders.md

Update from _then_ to _than_ on "We cannot give more information **then** this because things might change"

Fix small typo on docs

---

package.json

`jest-axe` is only used during testing, therefore it belongs in `devDependencies`.
This is normally not a big deal, aside from increased install time, but still.

Change jest-axe dependency to dev

---

stories/55-mixed-sizes.stories.js
stories/src/mixed-sizes/mixed-size-items.jsx
stories/src/mixed-sizes/mixed-size-lists.jsx

Relevant for testing #930. I'm getting this into `master` for testing different approaches

adding examples for mixed sizes

---

src/view/use-isomorphic-layout-effect.js

fixes #1623
Updated the the useIsomorphicLayoutEffect layout effect to check for window.document.createElement instead of just window.
That matches what both [React](https://github.com/facebook/react/blob/master/packages/shared/ExecutionEnvironment.js) and [Redux](https://github.com/reduxjs/react-redux/blob/master/src/utils/useIsomorphicLayoutEffect.js) are doing

Update useIsomorphicLayoutEffect check

---

stories/src/table/with-dimension-locking.jsx

The same boolean check is performed twice, once after the other.
This cleans up the example for readability and to fix redundancy.

Remove duplicate code in dimension locking example

---

src/state/get-droppable-over.js
test/unit/state/get-droppable-over/preferencing.spec.js

In cases where lists are extremely tall (in relation to their siblings) we need to make sure preferencing based on distance between center points still holds up.

Fix the distance calculation to support varied lists 

---

.eslintrc.js
package.json
src/native-with-fallback.js
src/view/use-announcer/use-announcer.js
yarn.lock

Number.isInteger is forbidden now. Object.assign is added to exceptions
globally.

Upgrade eslint-plugin-es5

---

.size-snapshot.json
package.json
yarn.lock

7.1 had some annoying issues like memory leaks, etc. (summarized in
their changelogs). I didn't find a Greenkeeper PR for this for some
reason. Currently we're just using resolutions in our project, but I
figured I might as well file an upstream fix!

Upgrade react-redux to 7.2.0

---

docs/patterns/tables.md

Fix typo, inconsistent object references, and unclear language.

Touch up copy

---

docs/guides/reparenting.md

The last line says ```We do not using reparenting out of the box because of this performance drawback.``` while it should be ```We do not recommend using reparenting out of the box because of this performance drawback.```

Fixed typo on documentation

---

src/state/create-store.js

**What:** Adds a name to the store for redux devtools
**Why:** Without a specified name redux devtools will display the document title.  This could be a little confusing if there are multiple libraries that, like this one, use redux devtools.  I think it would be helpful to specify a name.  This would make it immediately obvious to developers.

Adds name to store for devtools

---

docs/about/examples.md

Hi! I'm a novice at contributing to open source, so I apologize if I'm not doing this the right way, but I wanted to share this example with the community. I basically combined the "Simple DnD between two lists" example with the "Using with function components" example, and then added the ability to add a droppable area and add/delete an item into a new droppable area. It's not much, but I think it shows some of the awesome modularity and power of react-beautiful-dnd.
Happy to remove this PR and add the suggestion elsewhere if you let me know the best way to proceed. Or just ignore this and I'll continue on my merry way!
Thanks for the amazing library!! It's exactly what I was looking for.

Added codesandbox to examples in docs

---

docs/patterns/virtual-lists.md

Links to the documentation of the project and a fork of the react-window code sandbox.

Add react-virtuoso examples to virtual list doc

---

src/view/use-sensor-marshal/sensors/use-touch-sensor.js

This is not super important but found it misleading that the default exported function name was not matching the actual file name 🙂

Rename use-touch-sensor default export to useTouchSensor

---

docs/api/droppable.md

I think this is a mistake, because isDragging property does not exist in DroppableProvided type

Replaced provided.isDragging with snapshot.isDragging in droppable.md file.

---

docs/api/draggable.md

Style overrides should occur AFTER the spread of the style props, to match the guide.

Update draggable.md style spread example

---

docs/guides/setup-problem-detection-and-error-recovery.md

Fix small typo. 
Assuming a non-rbd /runtime error also _cancels_ any active drag.

Docs: Update setup-problem-detection-and-error-recovery.md

---

README.md
docs/about/examples.md
docs/guides/reparenting.md
docs/patterns/multi-drag.md
docs/patterns/tables.md
docs/patterns/virtual-lists.md
docs/support/community-and-addons.md

Change netlify.com to netlify.app due to deprecated automatic .com redirects
netlify.com urls don't work:
https://answers.netlify.com/t/deprecating-automatic-com-redirects/115442

Change netlify.com to netlify.app
