package.json

Moves @atlaskit/css-reset and storybook dep to devDeps
fixes #21

Move storybook deps to devDeps

---

README.md

updating readme with warning about position fixed

---

README.md

This commit is just added a link of the translation which is translated as Korean in leehyunggeun/react-beautiful-dnd-kr

Add a link of README.md by Korean

---

src/view/drag-handle/drag-handle-types.js
src/view/drag-handle/drag-handle.jsx
test/unit/view/drag-handle.spec.js
test/utils/user-input-util.js

This change fixes #62. I can see why safari does what it does - but custom browser behaviour like things makes me super sad. 
/cc @v0lkan

fixing force press interaction

---

.npmignore
README.md
package.json
src/index.js
src/types.js
src/view/drag-drop-context/drag-drop-context.jsx
src/view/drag-drop-context/index.js
src/view/drag-handle/index.js
src/view/draggable-dimension-publisher/index.js
src/view/draggable/draggable-types.js
src/view/draggable/index.js
src/view/droppable-dimension-publisher/index.js
src/view/droppable/droppable-types.js
src/view/droppable/index.js
src/view/moveable/index.js
stories/src/board/board.jsx
stories/src/board/column.jsx
stories/src/horizontal/author-app.jsx
stories/src/horizontal/author-item.jsx
stories/src/horizontal/author-list.jsx
stories/src/primatives/quote-item.jsx
stories/src/vertical-nested/quote-list.jsx
stories/src/vertical/quote-list.jsx
test/unit/view/moveable.spec.js
yarn.lock

Closes #63 
https://github.com/alexreardon/react-beautiful-dnd-flow-example

Exporting public flow types

---

README.md
src/state/create-store.js

This seems pretty standard for npm packages. Thoughts?

Adding npm badge to readme

---

stories/src/board/board.jsx

fixing board story by avoiding shared scroll container

---

.travis.yml

Closes #47 
Follows the steps outlined here: 
https://docs.travis-ci.com/user/deployment/npm/

travis will now release on tags from master

---

src/state/action-creators.js
src/state/dimension.js
src/state/get-drag-impact/in-foreign-list.js
src/state/get-drag-impact/in-home-list.js
src/state/is-within-visible-bounds-of-droppable.js
src/state/move-cross-axis/get-best-cross-axis-droppable.js
src/state/position.js
src/state/reducer.js
src/types.js
src/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js
src/view/draggable/draggable-types.js
src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx
src/view/droppable/droppable-types.js
src/view/moveable/moveable-types.js
stories/5-multiple-vertical-lists-story.js
stories/src/multiple-vertical/quote-app.jsx
stories/src/primatives/quote-list.jsx
test/unit/state/dimension.spec.js
test/unit/state/is-within-visible-bounds-of-droppable.spec.js
test/unit/state/position.spec.js
test/unit/view/unconnected-droppable-dimension-publisher.spec.js
test/utils/dimension.js

derp, the branch with the feature was pointed at this one...

Shared scrollable parents

---

README.md

As I was reviewing the docs for this terrific project, I noticed some misspelled words and various other fixable items.
Keep rocking, y'all!

[Docs] Makes various spelling/grammar corrections

---

src/view/drag-handle/sensor/create-touch-sensor.js
test/unit/view/drag-handle.spec.js

A late [defensive addition](https://github.com/atlassian/react-beautiful-dnd/pull/165/commits/081b9682a2daa64ca87612939705255cc3223fd2) was not tested thoroughly and prevented touch dragging from working altogether 🙃

fixing touch dragging

---

README.md

Adding a note about min-height for for droppables. I also did some minor doc cleanup - hard not to when looking at them!

adding warning about empty droppables. also minor doc cleanup

---

README.md
src/index.js
src/view/drag-handle/drag-handle-types.js
src/view/drag-handle/drag-handle.jsx
src/view/drag-handle/sensor/create-keyboard-sensor.js
src/view/drag-handle/sensor/create-mouse-sensor.js
src/view/drag-handle/sensor/create-touch-sensor.js
src/view/drag-handle/sensor/sensor-types.js
src/view/draggable/draggable-types.js
src/view/draggable/draggable.jsx
test/unit/integration/__snapshots__/server-side-rendering.spec.js.snap
test/unit/view/drag-handle.spec.js
test/unit/view/unconnected-draggable.spec.js

Closes #176 
Allows for both native scrolling as well as reordering on the same list
The PR also includes some flow fixes

Moving to long press only to start drag

---

README.md

updated 
*more than they would if they **where** just* 
to 
*more than they would if they **were** just*
---
❤️ the docs. Easily the best documented library I have come across.

doc: minor typo: where update to were

---

test/unit/view/drag-drop-context.spec.js

adding more tests for consumer redux usage

---

README.md

Flow URLs were missing protocol, so weren't linking to new Flow domain properly.

Fixes 'flowtype' URLs

---

src/state/dimension.js
src/state/get-droppable-over.js
test/unit/state/get-droppable-over.spec.js

fixing issue where get-droppable-over incorrectly calculates clipping

---

src/view/drag-handle/sensor/create-keyboard-sensor.js
src/view/drag-handle/sensor/create-mouse-sensor.js
src/view/drag-handle/sensor/create-touch-sensor.js
src/view/drag-handle/util/create-scheduler.js
test/unit/view/drag-handle.spec.js

A little cleanup. Also added some tests

simplification of drag handle scheduling

---

src/view/drag-drop-context/drag-drop-context.jsx
stories/20-super-simple-story.js
stories/src/board/board.jsx
stories/src/simple/simple.jsx

Render timing fix

---

src/view/drag-handle/sensor/create-mouse-sensor.js
test/unit/view/drag-handle.spec.js

no longer starting a mouse drag if a modifier key is pressed

---

test/browser/simple-vertical-list-with-keyboard.spec.js

https://github.com/atlassian/react-beautiful-dnd/issues/433

Increasing timeout to 1 minute as Travis CI is slow. Closes #433

---

README.md
src/view/drag-handle/drag-handle.jsx
src/view/drag-handle/util/focus-retainer.js
test/unit/view/unconnected-draggable.spec.js

addressing feedback from michael

---

src/state/droppable-dimension.js
src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx
stories/20-super-simple-story.js
stories/src/simple/simple-scrollable.jsx
test/unit/view/droppable-dimension-publisher.spec.js

Scrollable droppable now works correctly. Fixes #461

---

README.md

Struggled a bit to follow examples in storybook since my application doesn't use `flow`. Adding a simple example for others

Adding more examples

---

README.md

adding brand

---

README.md

Fix using a portal link url

---

package.json
yarn.lock

Update stylelint to version 9.2.1

---

website/package.json
website/src/components/ExampleWrapper.jsx
website/yarn.lock

Pulling in new version of codesandboxer, as well as pointing the example file fetching at master instead of a deleted side branch of mine.
Noticed another codesandboxer issue which I'm looking to fix and get out this week, so may be another PR.

Made website sandboxes point to master

---

README.md

Add chinese 🇨🇳 docs link and New translation UI

---

package.json
yarn.lock

Reverts atlassian/react-beautiful-dnd#601

Revert "Update rollup-plugin-size-snapshot to the latest version 🚀"

---

src/state/auto-scroller/can-scroll.js
src/state/auto-scroller/fluid-scroller.js
src/state/auto-scroller/jump-scroller.js
src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx
stories/20-super-simple-story.js
stories/src/simple/simple-scrollable.jsx
test/unit/state/auto-scroll/can-scroll.spec.js
test/unit/state/auto-scroll/fluid-scroller.spec.js

Accounting for cross axis scrollbars in auto scrolling. Fixes #628 

---

.travis.yml

🔗 https://github.com/travis-ci/travis-ci/issues/9885

build: update travis yml file to fix yarn global bin issue

---

src/view/drag-handle/util/get-drag-handle-ref.js

checking if the SVGElement constructor exists before using it. 

---

README.md

"Simple DnD between two lists" is updated with valid sandbox url

Updated README.md with valid sandbox url

---

.circleci/config.yml
package.json
test/browser/simple-vertical-list-with-keyboard.spec.js
yarn.lock

ci: :allthethings:, workflows, caching, faster CI :)

---

README.md

Adding more detail to droppable optimisation. Closes #660

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md

Adding getting started section. Closes #363

---

website/src/components/page-wrapper.jsx

Add mobile menu button

---

docs/patterns/tables.md

Link was directing to an old folder.

Fix non-working link

---

README.md

Markdown link was written the wrong way around.

Fix a link in the readme

---

README.md

Added the "Community" Section of the docs, and a link to the Glitch task app from issue #688. 
Let me know if you have any feedback!

Add Community Section, with link to Glitch™️ task app.

---

.size-snapshot.json
docs/guides/how-we-detect-scroll-containers.md
src/state/dimension-marshal/while-dragging-publisher.js
src/view/drag-handle/util/get-drag-handle-ref.js
src/view/droppable-dimension-publisher/get-closest-scrollable.js
src/view/droppable-dimension-publisher/get-env.js
test/unit/view/droppable-dimension-publisher/is-element-scrollable.spec.js
test/unit/view/droppable-dimension-publisher/util/shared.js

Better scroll container detection

---

src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list.js
test/unit/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list.spec.js

now adding placeholder room before doing cross axis visibility check

---

README.md
docs/guides/identifiers.md

docs for ids

---

ISSUE_TEMPLATE.md
docs/guides/common-setup-issues.md

common setup guide

---

.flowconfig

setting max workers

---

README.md
docs/guides/types.md

onDragBeforeStart -> onBeforeDragStart
OnDragBeforeStartResponder -> OnBeforeDragStartResponder

Fix typos in docs

---

docs/guides/using-inner-ref.md

closed with div instead of Person

Fix closing tag in docs

---

README.md

`A drag handle can be a the Draggable element itself` -> `A drag handle can be the Draggable element itself`

Minor Typo fix in Readme

---

README.md

Adds the Spectrum badge to the readme 👍

Join the community on Spectrum!

---

.storybook/decorator/pop-iframe.jsx

More storybook popping

---

test/unit/docs/content.spec.js
test/unit/docs/no-broken-links.spec.js

using * import to get around false positive for no default import

---

src/view/drag-handle/drag-handle-types.js
src/view/drag-handle/drag-handle.jsx
src/view/drag-handle/sensor/create-touch-sensor.js
src/view/drag-handle/sensor/sensor-types.js
src/view/draggable/connected-draggable.js
src/view/draggable/draggable-types.js
src/view/draggable/draggable.jsx
stories/src/primatives/quote-list.jsx
test/unit/view/connected-draggable/util/get-own-props.js
test/unit/view/drag-handle/block-drag-start-when-something-else-dragging.spec.js
test/unit/view/drag-handle/contenteditable.spec.js
test/unit/view/drag-handle/focus-management.spec.js
test/unit/view/drag-handle/nested-drag-handles.spec.js
test/unit/view/drag-handle/throw-if-svg.spec.js
test/unit/view/drag-handle/touch-sensor.spec.js
test/unit/view/drag-handle/util/wrappers.js
test/unit/view/draggable/secondary.spec.js
test/unit/view/draggable/util/get-props.js

Adding the ability to opt out of respecting force touch interactions. Closes #1022 #1021

Opt out of respecting force touch

---

docs/about/design-principles.md

【typo fixed】affordences ---> affordances

【typo fixed】affordences ---> affordances

---

src/view/use-drag-handle/use-drag-handle.js
src/view/use-drag-handle/use-validation.js
stories/src/primatives/quote-list.jsx
test/unit/view/draggable/validation/drag-handle.spec.js
test/unit/view/draggable/validation/inner-ref.spec.js
test/unit/view/draggable/validation/own-props.spec.js

Drag handle validation bug

---

.eslintrc.js
src/view/use-drag-handle/use-focus-retainer.js
test/unit/view/drag-handle/focus-management.spec.js

Closes issue raised by @pwolaq in #1194

fixing focus loss in drag handle

---

src/view/is-type-of-element/is-svg-element.js
test/unit/view/is-type-of-element/is-svg-element.spec.js

no longer crashing if SVGElement is not present

---

docs/api/draggable.md
docs/guides/common-setup-issues.md

adding docs about keys

---

.size-snapshot.json
docs/api/draggable.md
src/state/dimension-marshal/dimension-marshal.js

A bit of defence for using index in keys

---

src/view/use-drag-handle/sensor/use-touch-sensor.js

Fixes #1292
Details: https://twitter.com/alexandereardon/status/1125904207184187393

fixing firefox touch dragging

---

docs/support/community-and-addons.md

Regarding https://github.com/atlassian/react-beautiful-dnd/issues/623#issuecomment-491172652.

Add `react-beautiful-dnd-test-utils` to the community section

---

README.md

- Added link to PT translation repo

docs: pt-translation

---

README.md

update language links to use consistent text style (bold)

Fix inconsistent language link styling in README.md

---

docs/api/droppable.md

Should be 'whose', not 'who's'.

Fix small grammar mistake in droppable.md

---

docs/patterns/multi-drag.md

Fix spelling mistake in multi-drag.md

---

README.md

https://github.com/atlassian/react-beautiful-dnd/issues/1450
Just remove Chinese docs in README.md

Remove Chinese docs link

---

src/state/visibility/is-position-in-frame.js

This is just a minor thing. Looks like this is leftover from some refactoring.

Remove duplicate boolean checks

---

docs/patterns/tables.md

Update tables.md with grammar fix

---

src/view/use-sensor-marshal/use-sensor-marshal.js
test/unit/integration/drag-handle/shared-behaviours/lock-released-mid-drag.spec.js
test/unit/integration/drag-handle/shared-behaviours/lock-released-pre-drag.spec.js

Sensor issue

---

docs/guides/screen-reader.md

Minor edits, added role and role description notes, added aria-describedby example, added NVDA details.

Copy edit changes

---

docs/guides/responders.md

"Keep in mind that if you remove the dragging item or it's..."

Remove incomplete sentence

---

docs/patterns/virtual-lists.md

Clarified the documentation in the Virtual List page

Fix documentation grammar and example code issues

---

csp-server/app.jsx

Event listener for event securitypolicyviolation [:36] added in componentDidMount [:35] is never removed from document [:36] , remove it in lifecycle method 'componentWillUnmount'.

Remove an event listener in componentWillUnmount

---

README.md

Add a link in README.md with Greek

add documentation in greek

---

docs/api/drag-drop-context.md
src/index.js
src/view/use-sensor-marshal/index.js
src/view/use-sensor-marshal/use-sensor-marshal.js

Export default sensors and update the docs. Based on #1705 as I noticed the feedback wasn't addressed in the original PR for a while.
Fixes #1698.

Export default sensors

---

README.md

I created a Japanese version of the document

Add Japanese link

---

package.json

It solves:
#2416
#2426
#2428
Can we merge it and release new version to npm? I looked at all changes since last release and they were pure documentation.

Updated peerDependencies to react@^18

---

README.md

adding deprecation notice to readme
